---
- hosts: webservers
  become: yes
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisite packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Update apt and install Docker packages
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to Docker group (use 'runner' on GitHub Actions)
      user:
        name: runner
        groups: docker
        append: yes

    - name: Install Python Docker SDK
      pip:
        name: docker

    - name: Pull React app Docker image
      community.docker.docker_image:
        name: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}/react-app"
        source: pull
        tag: latest

    - name: Run React app container
      community.docker.docker_container:
        name: react-app
        image: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}/react-app:latest"
        state: started
        restart_policy: always
        ports:
          - "81:80"

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Overwrite NGINX index.html
      copy:
        content: "<html><body><h1>Hello from GitHub Actions + Ansible</h1></body></html>"
        dest: /var/www/html/index.html

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Allow UFW HTTP & port 81 traffic
      block:
        - name: Allow HTTP
          ufw:
            rule: allow
            port: "80"
            proto: tcp

        - name: Allow custom port 81
          ufw:
            rule: allow
            port: "81"
            proto: tcp
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Enable UFW and reload to apply rules
      ufw:
        state: enabled
        policy: allow
